### ISSUE TITLE
[polling] level3 messages are too large

### ISSUE THREAD

**Issue by blbradley** [blbradley/gdax_websocket_to_kafka#16]
Error:

```
2017-09-25 00:21:24,847 - apscheduler.executors.default - ERROR - Job "produce_level3_book (trigger: interval[0:00:30], next run at: 2017-09-25 00:21:52 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "polling.py", line 39, in produce_level3_book
    produce_book(3)
  File "polling.py", line 31, in produce_book
    value_schema=value_schema,
  File "/usr/local/lib/python3.6/site-packages/confluent_kafka/avro/__init__.py", line 74, in produce
    super(AvroProducer, self).produce(topic, value, key, **kwargs)
cimpl.KafkaException: KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Unable to produce message: Broker: Message size too large"}
```

**Comment by blbradley** [comment]
Some level 3 order book messages can be more than the default max message size.

This can be solved by increasing `` and ``. Keep in mind that these settings are per-topic. So, existing topics will possibly need these settings.
